plugins {
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

dependencies {
    implementation project(':core')
    compileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
    compileOnly "org.slf4j:slf4j-api:2.0.16"
    compileOnly files("${rootDir}/libs/baritone-api-fabric-1.19.0.jar")

    compileOnly fileTree(dir: 'libs/fabric-api', include: ['*.jar'])
    compileOnly fileTree(dir: "${System.getProperty('user.home')}/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries", include: ['**/*.jar'])
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from({
        project(':core').sourceSets.main.output.classesDirs
    })
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}
